version: "3"
services:
  gradle:
    image: 
    working_dir: /home/gradle/project
    volumes:
      - ./:/home/gradle/project
      - ~/.m2:/home/gradle/.m2
      - ~/.gradle:/home/gradle/.gradle

  node:
    image: opendigitaleducation/node:10
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ~/.npm:/.npm
        #    - ~/.npmrc:/home/node/.npmrc
        #    - ~/.bowerrc:/home/node/.bowerrc
        #    - ~/.gitconfig:/home/node/.gitconfig
