services:
  maven:
    image: maven:3.8.6-jdk-8
    user: "$DEFAULT_DOCKER_USER"
    working_dir: /usr/src/maven
    volumes:
      - ./:/usr/src/maven
      - ~/.m2:/var/maven/.m2
    environment:
      MAVEN_CONFIG: /var/maven/.m2
  load-tester:
    image: grafana/k6:master
    volumes:
      - ./src/test/stresstest:/home/k6/src
      - ./src/test/resources/data:/home/k6/data
    environment:
      ROOT_URL: http://localhost:8090
      DATA_ROOT_PATH: /home/k6/data
      MAX_DURATION: 45s
      USER_TTL: 20000
      NB_USERS: 500
      DELAY_BEFORE_SEND: 45000
      NB_MESSAGES: 10000
      ADMC_LOGIN: tom.mate
      ADMC_PASSWORD: password